<?php
/**
 * @return array
 */
function getZelda()
{
    return [
        [
            "id" => 1,
            "name" => "Breath of the Wild",
            "console" => ['WiiU', 'Nintendo Switch'],
            "image" => "http://localhost/THE03.Magazine/img/games/botw.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "The reinventor of the open world genre.",
        ],
        [
            "id" => 2,
            "name" => "Ocarina of Time",
            "console" => ['Nintendo 64', 'GameCube', 'Wii', '3DS', 'WiiU', 'Nintendo Switch'],
            "image" => "http://localhost/THE03.Magazine/img/games/oot.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Time travel to save Hyrule from certain doom.",
        ],
        [
            "id" => 3,
            "name" => "Majora's Mask",
            "console" => ['Nintendo 64', 'GameCube', 'Wii', '3DS', 'WiiU', 'Nintendo Switch'],
            "image" => "http://localhost/THE03.Magazine/img/games/mm.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Fight a creepy mask that plagues Termina!",
        ],
        [
            "id" => 4,
            "name" => "Link's Awakening",
            "console" => ['Gameboy', 'Gameboy Colour', '3DS', 'Nintendo Switch'],
            "image" => "http://localhost/THE03.Magazine/img/games/la.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Wake up, that's it just wake up it's that easy.",
        ],
        [
            "id" => 5,
            "name" => "A Link to the Past",
            "console" => ['SNES', 'GBA', 'Wii', '3DS', 'WiiU', 'Nintendo Switch'],
            "image" => "http://localhost/THE03.Magazine/img/games/lttp.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Travel to a dark version of Hyrule!",
        ],
        [
            "id" => 6,
            "name" => "The Legend of Zelda",
            "console" => ['NES', 'SNES', 'Wii', '3DS', 'Wii U', 'Nintendo Switch'],
            "image" => "http://localhost/THE03.Magazine/img/games/zelda1.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "You better have that guidebook on hand.",
        ],
        [
            "id" => 7,
            "name" => "The Legend of Zelda II",
            "console" => ['NES', 'SNES', 'Wii', '3DS', 'Wii U', 'Nintendo Switch'],
            "image" => "http://localhost/THE03.Magazine/img/games/zelda2.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "I AM BUG.",
        ],
        [
            "id" => 8,
            "name" => "Wind Waker",
            "console" => ['GameCube', 'Wii U'],
            "image" => "http://localhost/THE03.Magazine/img/games/ww.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "hmm cartoon boy make wind go brrr!",
        ],
        [
            "id" => 9,
            "name" => "Twilight Princess",
            "console" => ['GameCube', 'Wii', 'Wii U'],
            "image" => "http://localhost/THE03.Magazine/img/games/tp.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Still a better love story than twilight.",
        ],
        [
            "id" => 10,
            "name" => "Crossbow Training",
            "console" => ['Wii'],
            "image" => "http://localhost/THE03.Magazine/img/games/crossbow.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Absolute masterpiece.",
        ],
        [
            "id" => 11,
            "name" => "Skyward Sword",
            "console" => ['Wii', 'Wii U', 'Nintendo Switch'],
            "image" => "http://localhost/THE03.Magazine/img/games/ss.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "I hope you like motion controls.",
        ],
        [
            "id" => 12,
            "name" => "Minish Cap",
            "console" => ['GBA', '3DS', 'WiiU'],
            "image" => "http://localhost/THE03.Magazine/img/games/minish.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "reject big boi, become small :)",
        ],
        [
            "id" => 13,
            "name" => "Link between Worlds",
            "console" => ['3DS'],
            "image" => "http://localhost/THE03.Magazine/img/games/lbw.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "A Link to the Past, but not A Link to the Past and different.",
        ],
        [
            "id" => 14,
            "name" => "Triforce Heroes",
            "console" => ['3DS'],
            "image" => "http://localhost/THE03.Magazine/img/games/triforce.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Funny crossdressing co-op game!",
        ],
        [
            "id" => 15,
            "name" => "Four Swords",
            "console" => ['GameCube'],
            "image" => "http://localhost/THE03.Magazine/img/games/4s.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "The better co-op game, minus the crossdressing.",
        ],
        [
            "id" => 16,
            "name" => "Phantom Hourglass",
            "console" => ['DS'],
            "image" => "http://localhost/THE03.Magazine/img/games/ph.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Wind Waker but not that good.",
        ],
        [
            "id" => 17,
            "name" => "Spirit Tracks",
            "console" => ['DS'],
            "image" => "http://localhost/THE03.Magazine/img/games/st.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Phantom Hourglass but better and with trains.",
        ],
        [
            "id" => 18,
            "name" => "Hyrule Warriors",
            "console" => ['Wii U', '3DS', 'Nintendo Switch'],
            "image" => "http://localhost/THE03.Magazine/img/games/hw.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Zelda: Fanservice the Game.",
        ],
        [
            "id" => 19,
            "name" => "The Faces of Evil",
            "console" => ['CD-i'],
            "image" => "http://localhost/THE03.Magazine/img/games/cdi.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "Lamp Oil, Rope, Bombs? You want it? It's yours, my friend.
            As long as you have enough rupees. Sorry, Link.
            I can't give credit! Come back when you're a little... MMMMMMM... Richer!",
        ],
        [
            "id" => 20,
            "name" => "Rosy Rupeeland",
            "console" => ['DS'],
            "image" => "http://localhost/THE03.Magazine/img/games/tingle.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "???",
        ],
        [
            "id" => 21,
            "name" => "Sonic Lost World",
            "console" => ['WiiU'],
            "image" => "http://localhost/THE03.Magazine/img/games/sonic.png",
            "image2" => "http://localhost/THE03.Magazine/img/games/error.png",
            "quote" => "I don't think this counts..",
        ]
    ];
}